### ISSUE TITLE
How is Figure 3 in the paper plotted

### ISSUE THREAD

**Issue by Wang-Yanting** [tonychenxyz/selfie#2]
I really like your paper. Figure 3 presents information remarkably well, and I'm interested in how it was created. Specifically, I'd love to know which tool you used to highlight words in a sentence with their relevance scores. Thanks!

**Comment by tonychenxyz** [comment]
Thanks very much! I'm glad you liked our paper! For figure 3, we first used python to generate HTML code for highlight and then copied and paste the rendered HTML to Apple Keynotes to organize into the entire diagram.
