### ISSUE TITLE
How to get 'converted_weights_llama_chat7b'?

### ISSUE THREAD

**Issue by HiHqqqq** [tonychenxyz/selfie#4]
Hi! I really like this work. Could you please tell me how to get 'converted_weights_llama_chat7b' used in  Supervised Controls.ipynb? I tried supervised controls with llama2-7b-chat-hf, but the results differ from that provided in Supervised Controls.ipynb.

**Comment by tonychenxyz** [comment]
Hi!  llama2-7b-chat-hf should be the right one to use. Could you provide more information about how the results differ?

I got converted_weights_llama_chat7b from the old meta model downloading process of downloading their format first and then converted to huggingface format.
