### ISSUE TITLE
Code for relevancy score

### ISSUE THREAD

**Issue by 5eqn** [tonychenxyz/selfie#6]
Impressive work! I've noticed in [README.md](https://github.com/tonychenxyz/selfie?tab=readme-ov-file#updates) that "Code for relevancy score will be added soon", do you need help implementing this?

**Comment by tonychenxyz** [comment]
Hi! Sorry for the slow reply. Relevancy score has been implemented. The output df of interpret() now includes a column for token-wise relevancy score.
Thanks for your interest!
